# Utilise une image Node.js légère
FROM node:22-alpine

# Installe Chromium (ChromeHeadless)
RUN apk --no-cache add chromium

# Définit le répertoire de travail
WORKDIR /app

# Copie uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json angular.json tsconfig.json ./

# Installe les dépendances du projet
RUN npm install --no-cache

# Copie le reste du code source
COPY . .

# Définit la variable d'environnement pour ChromeHeadless
ENV CHROME_BIN=/usr/bin/chromium-browser

# Exécute les tests unitaires avec Karma et les tests d'intégration éventuels
ENTRYPOINT ["npm", "run", "test", "--", "--watch=false", "--browsers=ChromeHeadless"]
