services:

    database:
        container_name: db_test
        image: postgres:17-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: quizine_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            TZ: Europe/Paris
        tmpfs:
            - /var/lib/postgresql/data # Base temporaire pour les tests (réinitialisée à chaque run)
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            retries: 5
            interval: 3s
            timeout: 30s

    api:
        container_name: api_test
        build:
            context: ./api
            dockerfile: Dockerfile-test
        restart: on-failure
        depends_on:
            database:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/quizine_test
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_PROFILES_ACTIVE: test
            TZ: Europe/Paris
        tmpfs:
            - /tmp # Stocke les fichiers temporaires en RAM pour améliorer les performances et éviter l'écriture sur disque

    client:
        container_name: client_test
        build:
            context: ./client
            dockerfile: Dockerfile-test
        restart: no
        depends_on:
            - api
        environment:
            TZ: Europe/Paris