services:

    database:
        container_name: db
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_DB: quizine
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            TZ: Europe/Paris
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

    api:
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile-dev
        restart: unless-stopped
        depends_on:
            -   database
        volumes:
            - ./api:/app # Monte le code source pour un développement en live
            - gradle_cache:/root/.gradle # Préserve le cache des dépendances pour accélérer les builds
        ports:
            - "8080:8080"
            - "35729:35729"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/quizine
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_PROFILES_ACTIVE: dev
            TZ: Europe/Paris
            WATCHPACK_POLLING: true


    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile-dev
        restart: unless-stopped
        depends_on:
            - api
        volumes:
            - ./client:/app # Monte le code source pour un développement en live
            - node_cache:/app/node_modules # Préserve le cache des dépendances pour accélérer les builds
        ports:
            - "4200:4200"
        environment:
            CHOKIDAR_INTERVAL: 1000
            CHOKIDAR_USEPOLLING: true
            TZ: Europe/Paris


volumes:
    postgres_data:
    gradle_cache:
    node_cache: