# Build avec JDK et Gradle
FROM eclipse-temurin:21-jdk-alpine

# Définit le répertoire de travail
WORKDIR /app

# Copie uniquement les fichiers liés à la configuration Gradle (pour utiliser le cache Docker)
COPY gradle/ gradle/
COPY settings.gradle.kts build.gradle.kts gradlew ./

# Télécharge les dépendances sans compiler le code source
RUN ./gradlew dependencies --no-daemon  # ajouter || true si on veut passer les erreurs

# Copie le reste du code source
COPY src/ src/

# Port de l'application (application + LiveReload)
EXPOSE 8080 35729

# Commande par défaut en mode développement
ENTRYPOINT ["./gradlew", "bootRun"]