name: Security Scan

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    trivy-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Trivy
              run: |
                  sudo apt-get install -y wget
                  wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(dpkg --print-architecture).deb
                  sudo dpkg -i trivy_$(dpkg --print-architecture).deb

            # Scanner le Dockerfile
            - name: Scan Dockerfile for security issues
              run: trivy config --exit-code 1 .

            # Build l'image Docker avant de la scanner
            - name: Build Docker Image
              run: docker build -t my-app:latest .

            # Scanner l'image Docker générée
            - name: Scan Docker Image for vulnerabilities
              run: trivy image --exit-code 1 --severity CRITICAL my-app:latest
